language: generic
sudo: required
services:
  - docker
script:
  - curl -LO https://raw.githubusercontent.com/clearfraction/tools/master/build.sh && chmod +x build.sh
  - docker run --privileged --cap-add=SYS_ADMIN -v $(pwd):/home clearlinux:latest sh -c "cd /home && ./build.sh"
